version: "3.2"
services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 mapoverwatchproject.wsgi:application
    # command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver
    container_name: app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  nginx:
    image: nginx:1.18
    container_name: webserver
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./static_files/admin:/var/www/html/static/admin/
      - ./static_files/js:/var/www/html/js
      - ./static_files/maps:/var/www/html/maps
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - app