# Generated by Django 3.0.6 on 2020-06-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=120)),
                ('map_id', models.IntegerField()),
                ('map_type', models.CharField(choices=[('AS', 'Assult'), ('ES', 'Escort'), ('CN', 'Control'), ('EH', 'Escort Hybrid'), ('AR', 'Arena')], max_length=2)),
            ],
        ),
    ]
