# Generated by Django 3.0.6 on 2020-06-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapoverwatchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('image_map', models.CharField(max_length=120)),
                ('image_url', models.URLField(max_length=300)),
                ('image_order', models.IntegerField()),
                ('isTopDown', models.BooleanField(default=False)),
            ],
        ),
    ]
