# Generated by Django 3.0.6 on 2020-06-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapoverwatchapp', '0002_image_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_table',
            name='map_type',
            field=models.CharField(choices=[('AS', 'Assault'), ('ES', 'Escort'), ('CN', 'Control'), ('EH', 'Escort Hybrid'), ('AR', 'Arena')], max_length=2),
        ),
    ]
