# Generated by Django 3.0.6 on 2020-06-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapoverwatchapp', '0005_auto_20200608_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_table',
            name='image_id',
        ),
    ]
