# Generated by Django 3.0.6 on 2020-06-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapoverwatchapp', '0006_remove_image_table_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map_table',
            name='map_id',
        ),
    ]
